version: '3'

services:
  web:
    build: .
    ports:
      - "9001:9001"
    environment:
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-development}
        ConnectionStrings__Mongo: ${ConnectionStrings__Mongo:-development}
        MongoDb__Database: ${MongoDb__Database:-development}
        AppSettings__Secret: ${AppSettings__Secret:-development}
        GithubApi__Uri: ${GithubApi__Uri:-development}
        GithubApi__UserAgent: ${GithubApi__UserAgent:-development}
        GithubApi__Token: ${GithubApi__Token:-development}
        ASPNETCORE_URLS: ${ASPNETCORE_URLS:-development}